### PR TITLE
feat: 🎸 support angular v19

### PR DESCRIPTION
**Pull request by medbenmakhlouf**
BREAKING CHANGE: 🧨 drop support for angular < 19

✅ Closes: #208

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/jsverse/transloco/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

```
[X] Yes
[ ] No
```

### CODE REVIEW

**Comment by newaeonweb** [comment]
maybe this solution is not enough, I notice that some translations are broken. I mean the translation is lost.

**Comment by shaharkazaz** [comment]
Duplicate of #209

**Comment by newaeonweb** [comment]
@shaharkazaz I'm sorry I didn't see the other question, but I stand by my comment, just pumping out the versions isn't enough.
I'll take a closer look.

**Comment by shaharkazaz** [comment]
@newaeonweb all the tests seem to pass so it's interesting to find your regression.
Feel free to open a PR and cover these cases with tests as well, or at least provide more information ☺️

**Pull request closed without merging**
