### PR TITLE
fix: 🐛 marker extraction is not working

### PR DESCRIPTION
**Pull request by xemlock**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/jsverse/transloco/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #184 

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by kekel87** [comment]
Duplicate of https://github.com/jsverse/transloco-keys-manager/pull/182

**Comment by shaharkazaz** [comment]
@xemlock I appreciate the PR! 
@kekel87 This is resolved by your PR I've just merged correct?

**Comment by kekel87** [comment]
> @xemlock I appreciate the PR! @kekel87 This is resolved by your PR I've just merged correct?

Yes

**Comment by shaharkazaz** [comment]
Fixed in #182

**Pull request closed without merging**
