### PR TITLE
Bug: Support Angular v19

### PR DESCRIPTION
**Pull request by medbenmakhlouf**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ X] The commit message follows our guidelines: https://github.com/jsverse/transloco/blob/master/CONTRIBUTING.md#commit
- [ X] Tests for the changes have been added (for bug fixes / features)
- [ X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

```
[ ] Yes
[ X] No
```

### CODE REVIEW

**Comment by shaharkazaz** [comment]
@medbenmakhlouf Thanks! did you use the commit command?

**Comment by medbenmakhlouf** [comment]
@shaharkazaz , I think I didn't , should I revert my changes and do another one with npm run commit ?

**Comment by shaharkazaz** [comment]
@medbenmakhlouf Yes please 🙂  Can you please mark this as a breaking change as well? it's part of the steps when committing, just write there "support Angular v19"

**Comment by medbenmakhlouf** [comment]
@shaharkazaz , I tried to change message commit here, or better I created a new PR [here](https://github.com/jsverse/transloco-keys-manager/pull/210)  with respecting the npm run commit. if you are happy with new one, I will close this one.

**Comment by medbenmakhlouf** [comment]
@shaharkazaz, Do you have an idea of when you plan to release this? Thanks!

**Comment by shaharkazaz** [comment]
@medbenmakhlouf I'll do it as soon as I have some time, I think this week 🙂

**Pull request merged**
